name: fast_media_picker
description: Media picker based on Instagram's UI design.
version: 0.0.9
repository: https://github.com/furkansarihan/fast_media_picker

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  photo_manager: ^2.2.0-dev.5
  snapping_sheet_2: ^3.1.5
  permission_handler: ^9.2.0
  dismissible_page: ^0.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
